(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["GoogleTranslate"],{

/***/ "./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js&":
/*!***************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js& ***!
  \***************************************************************************************************************************************************************************************************************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n//\n/* harmony default export */ __webpack_exports__[\"default\"] = ({\n  data: function data() {\n    return {};\n  },\n  methods: {}\n});\n\n//# sourceURL=webpack:///./src/pages/pokemon/GoogleTranslate.vue?./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options");

/***/ }),

/***/ "./node_modules/cache-loader/dist/cjs.js?{\"cacheDirectory\":\"node_modules/.cache/vue-loader\",\"cacheIdentifier\":\"3d0a907c-vue-loader-template\"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true&":
/*!***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************!*\
  !*** ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"3d0a907c-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true& ***!
  \***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/*! exports provided: render, staticRenderFns */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"render\", function() { return render; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"staticRenderFns\", function() { return staticRenderFns; });\nvar render = function() {\n  var _vm = this\n  var _h = _vm.$createElement\n  var _c = _vm._self._c || _h\n  return _vm._m(0)\n}\nvar staticRenderFns = [\n  function() {\n    var _vm = this\n    var _h = _vm.$createElement\n    var _c = _vm._self._c || _h\n    return _c(\"div\", [\n      _c(\"h1\", [_vm._v(\"1. INSTALLATION\")]),\n      _c(\"p\", [\n        _vm._v(\n          \" Patch your Pokèmon Emerald English ROM (sha1: f3ae088181bf583e55daf962a92bb46f4f1d07b7) with Lunar IPS using the provided patch file. \"\n        )\n      ]),\n      _c(\"h1\", [_vm._v(\"2. DETAILS\")]),\n      _c(\"p\", [\n        _vm._v(\n          \" Translation sequence: English -> Russian -> Spanish -> Japanese -> Finnish -> Arabic -> Corsican -> Chinese (Simplified) -> English \"\n        )\n      ]),\n      _c(\"b\", { staticStyle: { \"text-align\": \"left\" } }, [\n        _vm._v(\"Text translated:\")\n      ]),\n      _c(\"ul\", { staticStyle: { \"text-align\": \"left\" } }, [\n        _c(\"li\", [_vm._v(\"Ability names\")]),\n        _c(\"li\", [_vm._v(\"Ability descriptions\")]),\n        _c(\"li\", [_vm._v(\"Natures\")]),\n        _c(\"li\", [_vm._v(\"Type names\")]),\n        _c(\"li\", [_vm._v(\"Move names\")]),\n        _c(\"li\", [_vm._v(\"Move descriptions\")]),\n        _c(\"li\", [_vm._v(\"Pokémon names\")]),\n        _c(\"li\", [_vm._v(\"Pokémon Pokédex descriptions\")]),\n        _c(\"li\", [_vm._v(\"Battle text\")]),\n        _c(\"li\", [_vm._v(\"Options menu\")]),\n        _c(\"li\", [_vm._v(\"Choice menus\")]),\n        _c(\"li\", [_vm._v(\"Start menu\")]),\n        _c(\"li\", [_vm._v(\"Dialog text\")]),\n        _c(\"li\", [_vm._v(\"Match call messages\")]),\n        _c(\"li\", [_vm._v(\"Trainer classes\")]),\n        _c(\"li\", [_vm._v(\"Trainer names\")]),\n        _c(\"li\", [_vm._v(\"Item names\")]),\n        _c(\"li\", [_vm._v(\"Item descriptions\")]),\n        _c(\"li\", [_vm._v(\"Credits\")]),\n        _c(\"li\", [_vm._v(\"Miscellaneous text\")])\n      ]),\n      _c(\"h1\", [_vm._v(\"3. Download\")]),\n      _c(\"a\", { attrs: { href: \"/Google translated Pokemon Emerald.zip\" } }, [\n        _vm._v(\"Click here\")\n      ])\n    ])\n  }\n]\nrender._withStripped = true\n\n\n\n//# sourceURL=webpack:///./src/pages/pokemon/GoogleTranslate.vue?./node_modules/cache-loader/dist/cjs.js?%7B%22cacheDirectory%22:%22node_modules/.cache/vue-loader%22,%22cacheIdentifier%22:%223d0a907c-vue-loader-template%22%7D!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options");

/***/ }),

/***/ "./src/pages/pokemon/GoogleTranslate.vue":
/*!***********************************************!*\
  !*** ./src/pages/pokemon/GoogleTranslate.vue ***!
  \***********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true& */ \"./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true&\");\n/* harmony import */ var _GoogleTranslate_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./GoogleTranslate.vue?vue&type=script&lang=js& */ \"./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js&\");\n/* empty/unused harmony star reexport *//* harmony import */ var _node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../../node_modules/vue-loader/lib/runtime/componentNormalizer.js */ \"./node_modules/vue-loader/lib/runtime/componentNormalizer.js\");\n\n\n\n\n\n/* normalize component */\n\nvar component = Object(_node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_2__[\"default\"])(\n  _GoogleTranslate_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_1__[\"default\"],\n  _GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__[\"render\"],\n  _GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__[\"staticRenderFns\"],\n  false,\n  null,\n  \"e5735736\",\n  null\n  \n)\n\n/* hot reload */\nif (false) { var api; }\ncomponent.options.__file = \"src/pages/pokemon/GoogleTranslate.vue\"\n/* harmony default export */ __webpack_exports__[\"default\"] = (component.exports);\n\n//# sourceURL=webpack:///./src/pages/pokemon/GoogleTranslate.vue?");

/***/ }),

/***/ "./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js&":
/*!************************************************************************!*\
  !*** ./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js& ***!
  \************************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _node_modules_cache_loader_dist_cjs_js_ref_12_0_node_modules_babel_loader_lib_index_js_node_modules_cache_loader_dist_cjs_js_ref_0_0_node_modules_vue_loader_lib_index_js_vue_loader_options_GoogleTranslate_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../../node_modules/cache-loader/dist/cjs.js??ref--12-0!../../../node_modules/babel-loader/lib!../../../node_modules/cache-loader/dist/cjs.js??ref--0-0!../../../node_modules/vue-loader/lib??vue-loader-options!./GoogleTranslate.vue?vue&type=script&lang=js& */ \"./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/pokemon/GoogleTranslate.vue?vue&type=script&lang=js&\");\n/* empty/unused harmony star reexport */ /* harmony default export */ __webpack_exports__[\"default\"] = (_node_modules_cache_loader_dist_cjs_js_ref_12_0_node_modules_babel_loader_lib_index_js_node_modules_cache_loader_dist_cjs_js_ref_0_0_node_modules_vue_loader_lib_index_js_vue_loader_options_GoogleTranslate_vue_vue_type_script_lang_js___WEBPACK_IMPORTED_MODULE_0__[\"default\"]); \n\n//# sourceURL=webpack:///./src/pages/pokemon/GoogleTranslate.vue?");

/***/ }),

/***/ "./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true&":
/*!******************************************************************************************!*\
  !*** ./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true& ***!
  \******************************************************************************************/
/*! exports provided: render, staticRenderFns */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _node_modules_cache_loader_dist_cjs_js_cacheDirectory_node_modules_cache_vue_loader_cacheIdentifier_3d0a907c_vue_loader_template_node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_cache_loader_dist_cjs_js_ref_0_0_node_modules_vue_loader_lib_index_js_vue_loader_options_GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! -!../../../node_modules/cache-loader/dist/cjs.js?{\"cacheDirectory\":\"node_modules/.cache/vue-loader\",\"cacheIdentifier\":\"3d0a907c-vue-loader-template\"}!../../../node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../../../node_modules/cache-loader/dist/cjs.js??ref--0-0!../../../node_modules/vue-loader/lib??vue-loader-options!./GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true& */ \"./node_modules/cache-loader/dist/cjs.js?{\\\"cacheDirectory\\\":\\\"node_modules/.cache/vue-loader\\\",\\\"cacheIdentifier\\\":\\\"3d0a907c-vue-loader-template\\\"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/pokemon/GoogleTranslate.vue?vue&type=template&id=e5735736&scoped=true&\");\n/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, \"render\", function() { return _node_modules_cache_loader_dist_cjs_js_cacheDirectory_node_modules_cache_vue_loader_cacheIdentifier_3d0a907c_vue_loader_template_node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_cache_loader_dist_cjs_js_ref_0_0_node_modules_vue_loader_lib_index_js_vue_loader_options_GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__[\"render\"]; });\n\n/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, \"staticRenderFns\", function() { return _node_modules_cache_loader_dist_cjs_js_cacheDirectory_node_modules_cache_vue_loader_cacheIdentifier_3d0a907c_vue_loader_template_node_modules_vue_loader_lib_loaders_templateLoader_js_vue_loader_options_node_modules_cache_loader_dist_cjs_js_ref_0_0_node_modules_vue_loader_lib_index_js_vue_loader_options_GoogleTranslate_vue_vue_type_template_id_e5735736_scoped_true___WEBPACK_IMPORTED_MODULE_0__[\"staticRenderFns\"]; });\n\n\n\n//# sourceURL=webpack:///./src/pages/pokemon/GoogleTranslate.vue?");

/***/ })

}]);